### ISSUE TITLE
Не работает mx player 

### ISSUE THREAD

**Issue by Andreich92** [lampa-app/LAMPA#13]
Вылетает ошибка и не включается mx player, другие плееры отлично работают
![Screenshot_2023-11-10-16-45-39-356_top rootu lampa](https://github.com/lampa-app/LAMPA/assets/150454667/c6aa7f54-b4a2-4def-b3f1-a4bc0cb7dff4)

**Comment by usmanec** [comment]
Перестановите MX плеер

**Comment by Andreich92** [comment]
Ок, попробую

вт, 28 нояб. 2023 г., 07:20 RootU ***@***.***>:

**Comment by Andreich92** [comment]
После обновы на 1.5.5 mx player заработал.

вт, 28 нояб. 2023 г., 12:23 Андрей Люлин ***@***.***>:
