### ISSUE TITLE
Lampa totally hangs during starting some video

### ISSUE THREAD

**Issue by xDzmShe** [lampa-app/LAMPA#15]
ТВ приставка Xiaomi Mi Box S 4K
Android TV (Android 12)
Проблема проявляется в Lampa 1.6.1, 1.6.0 и более старых.

Установлен плагин просмотра ТВ skaz.tv (в Lampa плагин добавляется по адресу http://skaztv.online/tv.js)

При запуске некоторых каналов (например Кинопремьера HD, Viju History HD) приложение Lampa полностью зависает: черный экран, приложение Lampa не реагирует ни на какие действия. Можно только выйти на главный экран Android TV и заново запустить приложение Lampa (Lampa загружается с самого начала).

Lampa зависает на Встроенном видео проигрывателе. На Mi TV Video Player - не удалось воспроизвести видео, на MX Player - сначала Буферизация, а затем черный экран, так же как и на Встроенном видео проигрывателе.

Проверял Lampa на смартфоне Xiaomi с Android 12 и всё работает без проблем (каналы, которые не работали на ТВ приставке, нормально открываются на смартфоне).

Есть ли возможность включить логирование и как-либо продиагностировать, где находится проблема?

**Comment by usmanec** [comment]
В первую очередь попробовать обратиться к разработчикам плагина, возможно он знает пути решения вашей проблемы.

Т.к. внутренний плеер - это плеер в вебвью (посути видео воспроизводится в браузере Google Chrome), количество поддерживаемых в нём кодеков ограничено самим гуглом и повлиять на это не получится. Именно из-за этого, на андройде, рекомендуется использовать внешний плеер.

Вы можете попробовать сменить в настройках лампы в разделе плеер обработку с системной на програмнную (или наоборот).

Проверьте так же какое вебвью используется в приложении, для этого нажмите кнопку меню на пульте или удерживайте кнопку назад, в появившемся меню выбрать смену браузера (на последних версиях андройда рекомендуется использовать Android System Webview, а Crosswalk - для старых версий андройда). Перед сменой вебвью там же можно сделать бекап настроек, после смены загрузить настройки для лампы. Если после смены браузера приложение перестанет запускаться, очистите данные приложения (если не знаете как, то можно удалить приложение и установить его заново).

P.S. В качестве внешнего плеера на вашем тв боксе рекомендую использовать "Медиаплеер Виму"  (доступен бесплатно для РФ в маркете на тв) или ViMu (для других стран). Приложение так же поддерживает плеера: Just (Video) Player; MPV-Android; VLC. Однако автопереключение серий доступно только на: Виму/ViMu; MX Player и UPlayer (Ugoos).
