### ISSUE TITLE
Custom Lampa URL doesn't allow format http://somename:5555

### ISSUE THREAD

**Issue by corker** [lampa-app/LAMPA#17]
I have Lampac installed in a docker container on a machine that is available on my home network with the name SOMENAME and is listening on port 9118
I can open Lampa in a web browser by navigating to http://somename:9118
But when I try to change the Lampa URL in the app, I get an error - please enter a valid Lampa URL.
I think the problem is in the URL validation regex on this line
https://github.com/lampa-app/LAMPA/blob/197da7f20268023274c431975ef1c21a8ca46158/app/src/main/java/top/rootu/lampa/MainActivity.kt#L150

**Comment by tsynik** [comment]
You need provide valid URL - in case of domain name it must be lampa.home, lampa.local lampa.lan etc
