### ISSUE TITLE
Не стартует после перезагрузки

### ISSUE THREAD

**Issue by taravasya** [lampa-app/LAMPA#19]
UGOOS AM6B
Lampa 1.6.3

После установки всё работает нормально.
Вхожу в аккаунт, настраиваю синхронизацию, всё работает ровно.
После перезагрузки приставки, не могу запустить приложение. Оно запускается и после появления логотипа, сразу же закрывается. Подозреваю, что виновен один из плагинов, так как без входа в аккаунт проблемы нет.
Может подскажете как можно узнать "виновника"? Может можно где-то логи посмотреть?

**Comment by SiamiX** [comment]
Устройства где проявилась проблема:
NVIDIA SHIELD TV Pro 2019
Китайский стик X98 S500

Lampa 1.6.3
CUB Premium приобретен

Аналогичная ситуация, после настройки приложения и входа в свой аккаунт CUB. При последующем запуске просто происходит вылет приложения. Переустановка не помогает. Сначала тоже думал, что проблема с каким-то из плагинов, но протестировал с плагинами, прописанными в CUB, отключал их и включал, ситуация не изменялась. Далее протестировал те же плагины, но без входа в аккаунт (прописав их вручную), и оказалось, что все работает прекрасно. Подозреваю что проблема с синхронизацией, так как вылеты прекращаются если перед выходом из приложения сменить профиль (те что с портала CUB) с "Основной" на любой другой, видимо в коллекции этого профиля присутствует что то, что приводит к вылету. На данном профиле много разных сериалов, не очень хотелось бы это все вручную удалять и затем заново добавлять, чтобы произвести тест. К слову, все работает без вылетов на ныне уже неподдерживаемой версии приложении для Android TV (7.7.9-115), да и pwa версии на iphone и ipad, и в приложении для windows все работает тоже, хотелось что бы разработчики поправили и это приложение.

**Comment by taravasya** [comment]
Да, я тоже убедился, что плагины ни при чём. Дело именно в синхронизации. И тоже есть старая версия Lampa TV, она работает стабильно.

**Comment by tsynik** [comment]
Без логов исправлять нечего. Нужно содержимое logcat устройства после вылета приложения

**Comment by taravasya** [comment]
Дыу вот как раз и вопрос, где и какие логи брать? Logcat? Много раз слышал этот термин, пойду прогуглю...

**Comment by SiamiX** [comment]
Слил logcat со стика x98_s500, если потребуется могу слить еще и с шилды
[logcat.txt](https://github.com/lampa-app/LAMPA/files/15053511/logcat.txt)

**Comment by tsynik** [comment]
> Слил logcat со стика x98_s500, если потребуется могу слить еще и с шилды.

Спасибо, исправление падения в 1.6.4, вызвано оно несоответствием данных типу:
```
04-21 19:27:01.684  3349  3393 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
04-21 19:27:01.684  3349  3393 E AndroidRuntime: Process: top.rootu.lampa, PID: 3349
04-21 19:27:01.684  3349  3393 E AndroidRuntime: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "7-8"
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:243)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:233)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:161)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:266)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:1058)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:1016)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:959)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:927)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at top.rootu.lampa.channels.WatchNext.updateWatchNext(WatchNext.kt:95)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at top.rootu.lampa.channels.LampaChannels$update$1$1.invokeSuspend(LampaChannels.kt:56)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
04-21 19:27:01.684  3349  3393 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by taravasya** [comment]
У меня со старой версией "Позже" отображались в ATV.

**Comment by tsynik** [comment]
> У меня со старой версией (которая Android TV 7.7.9-115) "Позже" отображались в ATV.

В случае использования аккаунта cub а не локального избранного? чота верится с трудом ;-)

**Comment by tsynik** [comment]
> У меня со старой версией (которая Android TV 7.7.9-115) "Позже" отображались в ATV.

В случае использования аккаунта cub а не локального избранного? чота верится с трудом ;-)

> Спасибо, все теперь работает как нужно, на моих 2-х устройствах не вылетает.
