### ISSUE TITLE
Видео во встроенном плеере фризится

### ISSUE THREAD

**Issue by 21vvvv** [lampa-app/LAMPA#2]
Онлайн Видео во встроенном плеере фризится после 5-10 минут просмотра. В логах ошибок нет. Возпроизводится и на телефоне и на телике. В Lampa 7.7.7 такого нет - все работает. 
В итоге пользоваться встроенным плеером не возможно. А внешний плеер не умеет переходить на след серию (на резке) и не сохраняет таймкод каждые N  секунд.

**Comment by usmanec** [comment]
Модели устройств напишите.
Проект Crosswalk давно отправлен в архив, поэтому он не тестировался на новых устройствах. Есть пара параметров, которые возможно улутшат ситуацию, если я сделаю тестовые сборки сможите протестировать? Если руки дойдут, возможно сделаю сборку с выбором что использовать Crosswalk (для старых устройств) или системный WebView (для новых).

Как вариант пользоваться внешним плеером Vimu/Виму/MX - в этих плеерах есть поддержка переключения серий и происходит сохранение таймкода в лампе при выходе из плеера.

Переключение серий в резке отсутствует, так как сам плагин не отдаёт список серий при запуске плеера (все вопросы к автору плагина, но скорее всего сделано это из-за того что ссылки в резке со временем "протухают").

**Comment by 21vvvv** [comment]
Внешний плеер не вариант потому что контроль над ним ограничен: при переходу на след серию нельзя подгрузить ее урл(); не сохраняется таймкод каждые N секунд и т п...

Вы пробовали воспроизвести? Устройства: телик Xiaomi Mi TV 4A 32, телефон redmi note 8 pro. Прошивки родные.

**Comment by tsynik** [comment]
> Xiaomi Mi TV 4A 32

странно что он в принципе играет торренты еще и встроенны плером - там все печально как с кодеками так и с оперативкой. возможно причина именно в нем. При использовании MX таймкоды должны сохраняться на 9-м андроиде в этом приложении.

**Comment by 21vvvv** [comment]
> > Xiaomi Mi TV 4A 32
> 
> странно что он в принципе играет торренты еще и встроенны плером - там все печально как с кодеками так и с оперативкой. возможно причина именно в нем. При использовании MX таймкоды должны сохраняться на 9-м андроиде в этом приложении.

речь идет про онлайн. Ладно бы зависало только в телике. В телефоне то же самое.

**Comment by tsynik** [comment]
> речь идет про онлайн. Ладно бы зависало только в телике. В телефоне то же самое.
И все же на это влияют только ОС и её декодеры и возможности по идее, и приложние никак не контролирует этот процесс, разве что занимает больше памяти и вот это исправить н выйдет.  Попробуй включить упрощенный режим в лампе и уменьшить кол-во хранимых страниц  с 5 до трех или одной.

**Comment by 21vvvv** [comment]
Попробовал еще раз воспроизвести на телефоне. Получилось не сразу. Не не всех видео есть этот баг. Но вот на этом стандартно воспроизводится через 5-10 мин:
![image](https://user-images.githubusercontent.com/113338481/190985135-e14ad750-232a-45b9-8621-f7ece703af7a.png)

Возможно это связано с кодеками, но опять же - на 7.7.7 все работает значит и у вас должно). 
 

> Попробуй включить упрощенный режим в лампе и уменьшить кол-во хранимых страниц с 5 до трех или одной.
Все поотключал - ничего не помогает.

**Comment by usmanec** [comment]
Ну только добавление системного WebView похоже может помочь как то улучшить ситуацию с плавностью.
Однако я всё же рекомендую пользоваться на андройде внешними плеерами - разработанными специально для воспроизведения потокового видео (в приложении полная (переключение серий и таймлайн) поддержка плееров Vimu/Виму/MX). Не пойму сценарий, где требуется сохранение прогресса каждые N секунд.

**Comment by 21vvvv** [comment]
> Не пойму сценарий, где требуется сохранение прогресса каждые N секунд.

Включаю ребенку мультсериал. Он смотрит N серий. Чеерз час приходит мама и в спешке выдергивает телик из розетки. На след день включаю телик и прогресс не сохранен и ребенок смотрит то же самое по второму кругу.

> Переключение серий в резке отсутствует, так как сам плагин не отдаёт список серий. 

Это бла бла на меня не действует... Я бы хотел иметь полный контроль над плеером и подгрузка урла видео при переключении на след серию выглядит логично.

Я понимаю что html видео плеер уступает нативному но для просмотра сериалов онлайн внешний плеер плохо подходит. Может у вас есть идеи как нативный плеер(с открытыми исходниками) лучше интегрировать в лампу чтобы иметь над ним полный контроль.

**Comment by msergein** [comment]
>Это бла бла на меня не действует... 

🤦‍♂️

**Comment by tsynik** [comment]
Встроенный в лампу плеер - не для андроида

**Comment by tsynik** [comment]
NP
