### ISSUE TITLE
Каналы для AndroidTV

### ISSUE THREAD

**Issue by ApXuBaToP** [lampa-app/LAMPA#20]
Добрый день. Сейчас приложение прддервает вывод 4ёх категорий: Закладки, Нравится, История и Рекомендации. Есть возможность добавить каналы по меткам: Я смотрю, Позже, Запланировано и т.д.? 

Заранее спасибо

**Comment by tsynik** [comment]
> Добрый день. Сейчас приложение прддервает вывод 4ёх категорий: Закладки, Нравится, История и Рекомендации. Есть возможность добавить каналы по меткам: Я смотрю, Позже, Запланировано и т.д.?

Возможность есть, но эти функции не доступны по-умолчанию, и было бы странно показывать их без возможности использования. Может, сделаем с проверкой доступности позже.

**Comment by tsynik** [comment]
https://github.com/lampa-app/LAMPA/releases/tag/v1.7.3

**Comment by ApXuBaToP** [comment]
Топчик!  Спасибо :)
