### ISSUE TITLE
При сворачивании встроенного плеера видео продолжает играть

### ISSUE THREAD

**Issue by 21vvvv** [lampa-app/LAMPA#3]
При сворачивании встроенного плеера видео продолжает играть (слышен звук). При блокировке экрана аналогично. В Lampa 7.7.7 все работает как надо. При сворачивании останавливается при разворачивании продолжается.

**Comment by usmanec** [comment]
Спасибо за обращение. Изначально не делалась ставка на внутренний плеер, но посмотрю что можно и можно ли в Crosswalk что-то сделать.

**Comment by 21vvvv** [comment]
Спасибо за ответ. А Crosswalk уступает  webView? Или есть преимущества?

**Comment by usmanec** [comment]
Единственное преимущество Crosswalk, то что он позволяет запустить относительно современные сайты на андройдах от версии 4.1 (т.к. системный WebView до 5го андройда был не обновляемый и сильно устарел).

Посути это тоже хром (точнее хромиум), что и современный WebView за одним исключением - к сожалению, дальнейшее развитие остановлено на 53 версии хромиума и в 2019 году проект отправлен в архив https://github.com/crosswalk-project

**Comment by tsynik** [comment]
NP
