### ISSUE TITLE
Приложение не запускается

### ISSUE THREAD

**Issue by Immick** [lampa-app/LAMPA#9]
Приветствую!

На Samsung S10e со Snapdragon 855 (Android 12) актуальная на сегодняшний момент Лампа (1.3.5) вылетает при старте. Перед запуском было предложено скачать Crosswalk, тот скачался, что-то сообщил про несовместимость (в GP, кстати, он недоступен для скачивания вообще, т.к. не поддерживается версий), но в итоге установился.

Можно ли это как-то исправить?

Спасибо!

P.S. Знаю, что в качестве альтернативы для телефона есть LampaTV (актуальная версия v7.7.9-112), однако там имеется недоработка по поводу использования буфера предзагрузки для встроенного клиента (тип плеер - Android) - буфер предзагрузки просто игнорируется. Подумал, что может быть в "чисто" андройдной версии с буфером все нормально...

**Comment by usmanec** [comment]
Проблема именно с андройдом 12 на телефонах самсунг и хуавей(на других телефонах с андройд 12 не замечено), Ошибка из [crosswalk](https://github.com/crosswalk-project/crosswalk) (проект уже не поддерживается). Могу посоветовать только использовать альтернативное приложение или обновите прошивку на телефоне до андройд 13.

P.S. Проблема с буфером не в андройд приложении, а в реализации самой лампы.
